### ISSUE TITLE
[META] SubstrateHost

### ISSUE THREAD

**Issue by seunlanlege** [polytope-labs/hyperbridge#72]
To support SubstrateHosts. We would need 

- [x] `HyperbridgeDispatcher` - for dispatching requests to hyperbridge
- [x] `SubstrateHostManager` -  for managing the `HostParams` from hyperbridge
- [x] ismp-grandpa - for standalone chains and parachains on the sister relay chain
- [ ] ismp-beefy - for standalone chains and parachains on the sister relay chain
- [x] ismp-parachain - for parachains

**Comment by MrishoLukamba** [comment]
So I need some clarification on this Issue as I intend to work on them.
My questions:
1. Hyperbridge dispatcher -> What requests does it submit to hyperbridge runtime?
2. Are all these functions in the host a way to migrate defined functionality from the runtime to the host and just dispatch the functions from the runtime enviroment?

@seunlanlege @Wizdave97

**Comment by Wizdave97** [comment]
Hey @MrishoLukamba you can start out with the`BEEFY` consensus client for ismp, we are still working on fully defining how we want the `HyperbridgeDispatcher` and `SubstrateHostManager` to work.

**Comment by seunlanlege** [comment]
closed in #192
